#!/bin/bash -x
# Recreate the map bundle, and merge in the regional vector subsets

# first check that the environment has been set
MG=${MG_SSD}
if [ "$MG" == "" ];then
   echo "Have you set the environment variables via 'source ./setenv'"
   exit 1
fi

