#!/bin/bash -x
# fetch updated copies of resources needed for vector OSM
# script runs to completion in 26 minutes on hadron

# may need some tools from iiab-factory
scriptdir=`dirname "$(readlink -f "$0")"`

#prefix=./
if [ "$MG_HARD_DISK" == "" ];then
   echo "Have you run the 'source ./setenv' which will define config?"
   exit 1
fi
prefix=$MG_HARD_DISK/output/stage3/fromscratch
read -p "Working directory is $prefix. Is that correct?" dummy
if [ $dummy != "y" ];then
   exit 1
fi

# create a place to put accumulations of resources
mkdir -p $prefix/assets/fonts
mkdir -p $prefix/build
cd $prefix/build

if [ ! -d maps ]; then
git clone https://github.com/iiab/maps
fi
cp -rp maps/* ..
if [ ! -d "openlayers" ]; then
git clone https://github.com/openlayers/openlayers
fi
if [ ! -d "jquery" ]; then
git clone git://github.com/jquery/jquery.git
fi
if [ ! -d "bootstrap" ]; then
git clone git://github.com/twitter/bootstrap.git
fi
if [ ! -d "bootstrap-ajax-typeahead" ]; then
git clone git://github.com/biggora/bootstrap-ajax-typeahead.git
fi
if [ ! -d "osm-bright-gl-style" ]; then
git clone git://github.com/openmaptiles/osm-bright-gl-style --branch gh-pages
fi

wget -P $prefix/assets https://unpkg.com/ol-mapbox-style@3.6.2/dist/olms.js
wget -P $prefix/assets https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v5.3.0/build/ol.js

wget -P $prefix/assets https://github.com/openlayers/openlayers.github.io/tree/master/en/v5.3.0/build/ol.css
 
pushd jquery
if [ ! -f dist/jquery.min.js ]; then
npm run build
fi
cp $prefix/build/jquery/dist/jquery.min.js $prefix/assets
popd

cp $prefix/build/bootstrap/dist/js/bootstrap.min.js $prefix/assets
cp $prefix/build/bootstrap/dist/css/bootstrap.min.css $prefix/assets
 
cp $prefix/build/bootstrap-ajax-typeahead/js/bootstrap-typeahead.min.js $prefix/assets/


# generate the fonts for offline use
if [ ! -d fonts ];then
git clone https://github.com/openmaptiles/fonts
cd fonts

npm install
node ./generate.js
fi
cp -r $prefix/build/fonts/_output/* $prefix/assets/fonts

# get the cities sqlite database
cd $prefix/build
if [ ! -f cities1000.zip ]; then
wget  http://download.geonames.org/export/dump/cities1000.zip
unzip cities1000.zip
fi
rm -f cities1000.sqlite
cp $scriptdir/mkfeatures.sql .
cp $scriptdir/geodb.pl .
sqlite3 cities1000.sqlite < mkfeatures.sql
$prefix/build/geodb.pl
cp cities1000.sqlite ..

if [ ! -f ocean.mbtiles ]; then
wget  http://download.iiab.io/packages/OSM/ocean.mbtiles
fi
cp ocean.mbtiles ..


cp $prefix/build/osm-bright-gl-style/sprite* $prefix/assets
